export const agentCopy = {
	en: {
		title: 'Agent access',
		detail: 'Connect your agent to this workspace through MCP or the CLI.',
		create: 'Create token',
		name: 'Name',
		nameHint: 'e.g. Codex on my laptop',
		scope: 'Access',
		read: 'Read only',
		write: 'Read and write',
		full: 'Full workspace access',
		fullHint: 'All workspace actions allowed by your current role. Token management stays in the app.',
		readHint: 'Read issues, projects and delivery plans.',
		writeHint: 'Also create and update work. Your workspace permissions still apply.',
		expiry: 'Expires in days',
		creating: 'Creating…',
		cancel: 'Cancel',
		close: 'Done',
		retry: 'Retry',
		loading: 'Loading tokens…',
		loadFailed: 'Could not load tokens.',
		createFailed: 'Could not create token. Try again.',
		empty: 'Connect your first agent',
		emptyDetail: 'Create a read-only token to get started.',
		secretTitle: 'Save your token',
		secretHint: 'Copy it now. Closing this window clears it; it cannot be shown again.',
		copyToken: 'Copy token',
		copied: 'Copied',
		copyFailed: 'Could not copy. Select and copy the text manually.',
		revoke: 'Revoke',
		revoking: 'Revoking…',
		revokeTitle: 'Revoke access?',
		revokeHint: 'This agent will stop connecting immediately.',
		revokeFailed: 'Could not revoke token. Try again.',
		active: 'Active',
		noActive: 'No active tokens',
		history: 'Expired and revoked',
		expired: 'Expired',
		revoked: 'Revoked',
		expires: 'Expires',
		used: 'Last used',
		never: 'Not used yet',
		guide: 'Connect an agent',
		guideHint: 'Install the CLI from source, then add this configuration to your MCP client.',
		build: 'Build from a source checkout',
		config: 'MCP configuration',
		client: 'Agent client',
		codexToken:
			'Set SPRINTORIO_TOKEN in your environment before starting Codex. The configuration forwards it without saving the secret.',
		remote: 'Remote agents · Grok',
		remoteHint:
			'Run the MCP server behind HTTPS. In Grok or another remote client, use your public /mcp URL and Authorization: Bearer YOUR_TOKEN. Each caller supplies its own token.',
		copyConfig: 'Copy configuration',
		endpoint: 'Server URL',
		endpointHint:
			'Use the Sprintorio server reachable by your agent. For remote agents, replace localhost with your server address.',
		tokenHint: 'Replace YOUR_TOKEN with the token you copied. Keep it in your client’s private configuration.',
		cli: 'CLI connection',
		personal: 'Tokens belong to your account in this workspace.'
	},
	it: {
		title: 'Accesso agenti',
		detail: 'Collega il tuo agente a quest’area di lavoro via MCP o CLI.',
		create: 'Crea token',
		name: 'Nome',
		nameHint: 'es. Codex sul mio computer',
		scope: 'Accesso',
		read: 'Solo lettura',
		write: 'Lettura e scrittura',
		full: 'Accesso completo all’area di lavoro',
		fullHint: 'Tutte le azioni consentite dal tuo ruolo attuale. Gestisci i token nell’app.',
		readHint: 'Leggi attività, progetti e piani di consegna.',
		writeHint: 'Crea e aggiorna anche il lavoro. Restano validi i tuoi permessi nell’area di lavoro.',
		expiry: 'Scade tra giorni',
		creating: 'Creazione…',
		cancel: 'Annulla',
		close: 'Fatto',
		retry: 'Riprova',
		loading: 'Caricamento token…',
		loadFailed: 'Impossibile caricare i token.',
		createFailed: 'Impossibile creare il token. Riprova.',
		empty: 'Collega il primo agente',
		emptyDetail: 'Inizia con un token di sola lettura.',
		secretTitle: 'Salva il token',
		secretHint: 'Copialo ora. Chiudendo questa finestra verrà cancellato e non potrai più visualizzarlo.',
		copyToken: 'Copia token',
		copied: 'Copiato',
		copyFailed: 'Impossibile copiare. Seleziona e copia il testo manualmente.',
		revoke: 'Revoca',
		revoking: 'Revoca…',
		revokeTitle: 'Revocare l’accesso?',
		revokeHint: 'L’agente smetterà subito di collegarsi.',
		revokeFailed: 'Impossibile revocare il token. Riprova.',
		active: 'Attivo',
		noActive: 'Nessun token attivo',
		history: 'Scaduti e revocati',
		expired: 'Scaduto',
		revoked: 'Revocato',
		expires: 'Scadenza',
		used: 'Ultimo utilizzo',
		never: 'Mai utilizzato',
		guide: 'Collega un agente',
		guideHint: 'Installa la CLI dai sorgenti e aggiungi questa configurazione al tuo client MCP.',
		build: 'Compila da una copia dei sorgenti',
		config: 'Configurazione MCP',
		client: 'Client agente',
		codexToken:
			'Imposta SPRINTORIO_TOKEN nell’ambiente prima di avviare Codex. La configurazione lo inoltra senza salvare il segreto.',
		remote: 'Agenti remoti · Grok',
		remoteHint:
			'Avvia il server MCP dietro HTTPS. In Grok o un altro client remoto, usa l’URL pubblico /mcp e Authorization: Bearer YOUR_TOKEN. Ogni client invia il proprio token.',
		copyConfig: 'Copia configurazione',
		endpoint: 'URL server',
		endpointHint:
			'Usa il server Sprintorio raggiungibile dal tuo agente. Per agenti remoti, sostituisci localhost con l’indirizzo del server.',
		tokenHint: 'Sostituisci YOUR_TOKEN con il token copiato. Conservalo nella configurazione privata del client.',
		cli: 'Connessione CLI',
		personal: 'I token appartengono al tuo account in quest’area di lavoro.'
	}
};
