export const experienceCopy = {
	en: {
		loading: 'Loading workspace…',
		failed: 'Could not load your workspace.',
		retry: 'Retry',
		start: 'Start your workspace',
		detail: 'Create a team, then add your first issue.',
		issueDetail: 'Add your first issue.',
		team: 'Create team',
		issue: 'Create issue',
		project: 'Create project',
		members: 'Add members',
		agents: 'Connect agents',
		later: 'Later',
		memberHint: 'Members need an existing Sprintorio account.',
		memberAdded: 'Member added',
		memberFailed: 'Could not add member',
		addMember: 'Add member',
		address: 'Workspace URL',
		ready: 'Your workspace is ready',
		teamDone: 'Team created',
		projectHint: 'Projects group issues around a shared goal.'
	},
	it: {
		loading: 'Caricamento area di lavoro…',
		failed: 'Impossibile caricare l’area di lavoro.',
		retry: 'Riprova',
		start: 'Inizia a lavorare',
		detail: 'Crea un team, poi aggiungi la prima attività.',
		issueDetail: 'Aggiungi la prima attività.',
		team: 'Crea team',
		issue: 'Crea attività',
		project: 'Crea progetto',
		members: 'Aggiungi membri',
		agents: 'Collega agenti',
		later: 'Più tardi',
		memberHint: 'I membri devono avere un account Sprintorio.',
		memberAdded: 'Membro aggiunto',
		memberFailed: 'Impossibile aggiungere il membro',
		addMember: 'Aggiungi membro',
		address: 'URL area di lavoro',
		ready: 'L’area di lavoro è pronta',
		teamDone: 'Team creato',
		projectHint: 'I progetti raggruppano attività con un obiettivo comune.'
	}
};
